name: Reqnroll Tests with C# Video Recording (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11-utils ffmpeg

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run Reqnroll tests with C# video recording
      run: |
        # Start virtual display
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1696x24 &
        sleep 3  # give Xvfb time to initialize

        # Run tests
        dotnet test --configuration Release
      shell: bash

    - name: Upload video recordings
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Reqnroll-Test-Videos
        path: bin/Release/net8.0/Reports/Results/Videos
        retention-days: 7
