name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils ffmpeg

      - name: Ensure video folder exists
        run: mkdir -p GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos

      - name: Restore dependencies
        run: dotnet restore --use-current-runtime

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: |
          # Start virtual framebuffer for headless browser rendering
          Xvfb :99 -screen 0 1280x1696x24 &
          export DISPLAY=:99
          # Suppress xkb warnings
          export XKB_DEFAULT_RULES=base
          sleep 2
          dotnet test --no-build --verbosity normal --configuration Release

      - name: Upload video reports
        if: always()
        run: |
          VIDEOS_DIR="GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos"
          if [ -d "$VIDEOS_DIR" ] && [ "$(ls -A $VIDEOS_DIR)" ]; then
            echo "Uploading videos..."
            echo "$VIDEOS_DIR"
          else
            echo "No video files found in $VIDEOS_DIR"
            exit 0
          fi
        uses: actions/upload-artifact@v4
        with:
          name: VideoReports
          path: GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos/**/*
