name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Install Linux dependencies + FFmpeg + Mesa + Xvfb
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfontconfig1 \
            libfreetype6 \
            libx11-6 \
            libxext6 \
            libxrender1 \
            libxcb1 \
            libx11-xcb1 \
            libxcomposite1 \
            libxrandr2 \
            libxi6 \
            libice6 \
            libsm6 \
            libc6-dev \
            libglib2.0-0 \
            ffmpeg \
            libosmesa6-dev \
            mesa-utils \
            xvfb

      # Start virtual framebuffer for SkiaSharp
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run inside Xvfb environment
      - name: Run Tests
        run: |
          export DISPLAY=:99
          dotnet test --no-build --configuration Release

      - name: Upload video reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: VideoReports
          path: GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos/**
