name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Cache FFmpeg binary
      - name: Cache FFmpeg
        id: ffmpeg-cache
        uses: actions/cache@v3
        with:
          path: ~/ffmpeg
          key: ffmpeg-ubuntu-latest
      - name: Install FFmpeg
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/ffmpeg
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          cp /usr/bin/ffmpeg ~/ffmpeg/
      - name: Add FFmpeg to PATH
        run: echo "$HOME/ffmpeg" >> $GITHUB_PATH

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-packages-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-packages-

      # Restore project dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Cache build output
      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            **/bin
            **/obj
          key: build-output-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            build-output-

      # Build the project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release

      # Upload recorded video reports
      - name: Upload video reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: VideoReports
          path: GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos/**
