name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Install FFmpeg
      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      # Install SkiaSharp native Linux dependencies
      - name: Install SkiaSharp dependencies
        run: sudo apt-get install -y libgl1-mesa-dev libfontconfig1 libice6 libsm6

      # Restore project dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release

      # Upload recorded video reports
      - name: Upload video reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: VideoReports
          path: GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos/**
