name: Reqnroll Tests with C# Video Recording (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Xvfb and FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11-utils ffmpeg

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run Reqnroll tests with C# video recording
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
          dotnet test --configuration Release
      shell: bash

    - name: Upload video recordings
      uses: actions/upload-artifact@v4
      with:
        name: Reqnroll-Test-Videos
        path: bin/Release/net8.0/Reports/Results/Videos
        retention-days: 7
