name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11-utils ffmpeg

    - name: Restore dependencies
      run: dotnet restore --use-current-runtime

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: |
        # Start virtual framebuffer to allow browser rendering
        Xvfb :99 -screen 0 1280x720x24 &
        export DISPLAY=:99
        dotnet test --no-build --verbosity normal --configuration Release

    - name: Debug — List all files
      if: always()
      run: |
        echo "Listing all files in workspace for debugging..."
        find . -type f | sort

    - name: Upload video recordings (if exists)
      if: always()
      run: |
        if [ -d "$(find . -type d -path '*/Reports/Results/Videos' | head -n 1)" ]; then
          echo "Videos folder found, uploading..."
          VIDEOS_DIR=$(find . -type d -path '*/Reports/Results/Videos' | head -n 1)
          echo "Found at: $VIDEOS_DIR"
          tar -czf videos.tar.gz -C "$VIDEOS_DIR" .
          echo "Uploading videos.tar.gz"
        else
          echo "No videos found, skipping upload."
          exit 0
        fi
      shell: bash

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Videos
        path: videos.tar.gz
        retention-days: 7
