name: CI with Headless Video Recording

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install FFmpeg and Xvfb
        run: sudo apt-get update && sudo apt-get install -y ffmpeg xvfb

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Start Virtual Display for Recording
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          sleep 3
        env:
          DISPLAY: :99

      - name: Run Tests in Headless Mode with Video
        run: dotnet test --configuration Release --verbosity normal
        env:
          HEADLESS_MODE: true
          DISPLAY: :99

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-videos
          path: ${{ github.workspace }}/Reports/Results/Videos/**/*.mp4
          retention-days: 5
