name: Reqnroll Tests with C# Video Recording (FFmpeg)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: windows-latest # Use Windows runner for potential dependencies with your C# code

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specify your .NET SDK version

    - name: Install FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1 # Action to install FFmpeg on Windows, macOS, and Ubuntu runners
      with:
        version: latest # Install the latest release version of FFmpeg

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run Reqnroll tests with C# video recording
      run: |
        # Assume your C# code handles starting and stopping FFmpeg
        dotnet test --configuration Release 
        # The test executable is at bin\Release\net8.0, and the videos are saved to bin\Release\net8.0\Reports\Results\Videos
        # Therefore, the videos will be relative to the test executable's directory.
      shell: pwsh # Use PowerShell on Windows runners

    - name: Upload video recordings
      uses: actions/upload-artifact@v4
      with:
        name: Reqnroll-Test-Videos
        path: bin/Release/net8.0/Reports/Results/Videos # Path to the directory containing your recorded videos
        retention-days: 7 # Optional: Set retention days for the artifact
