name: CI with Video Recording

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Or your .NET version

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg xvfb

    - name: Start Xvfb (Virtual Display)
      run: Xvfb :99 -screen 0 1280x1024x24 & # Match this resolution to your code's -video_size
      env:
        DISPLAY: :99 # Set DISPLAY for subsequent steps

    - name: Run Tests with Video Recording
      run: |
        dotnet test --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings "coverlet.runsettings"
      env:
        DISPLAY: :99 # Ensure DISPLAY is set for tests
        // For example: HEADLESS_MODE=true

    - name: Upload Videos (if any)
      uses: actions/upload-artifact@v4
      if: always() # Upload even if tests fail
      with:
        name: test-videos
        path: ${{ github.workspace }}/Reports/Results/Videos/**/*.mp4 # Adjust path as needed
        retention-days: 5
