name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install system dependencies (Xvfb, ffmpeg, libgdiplus, fonts)
        run: |
          sudo apt-get update
          # install Xvfb/ffmpeg and native libgdiplus + fonts for System.Drawing on Linux
          sudo apt-get install -y xvfb x11-utils ffmpeg libgdiplus fonts-liberation libx11-6 libxrender1
          # show versions for quick debugging
          echo "ffmpeg version:"
          ffmpeg -version
          echo "libgdiplus present:"
          ldconfig -p | grep libgdiplus || true

      - name: Restore dependencies
        run: dotnet restore --use-current-runtime

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Upload video reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: VideoReports
          path: GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos/** 
