name: Reqnroll Tests with C# Video Recording (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use Ubuntu runner for Linux environment

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Xvfb and FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb # Install Xvfb for the virtual display
        # The AnimMouse/setup-ffmpeg action already installs FFmpeg: https://github.com/marketplace/actions/setup-ffmpeg-action
        # So we just need to install Xvfb here.

    - name: Install FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
      with:
        version: latest # Install the latest release version of FFmpeg

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run Reqnroll tests with C# video recording
      run: |
        # Start Xvfb and run your tests within the virtual display
        # The DISPLAY variable directs graphical output to the Xvfb screen
        xvfb-run --auto-display --server-args="-screen 0 1920x1080x24" dotnet test --configuration Release 
      shell: bash


    - name: Upload video recordings
      uses: actions/upload-artifact@v4
      with:
        name: Reqnroll-Test-Videos
        path: bin/Release/net8.0/Reports/Results/Videos # Path to your video files
        retention-days: 7
