name: Video Recording Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11-utils ffmpeg

    - name: Restore dependencies
      run: dotnet restore --use-current-runtime

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Upload video recordings
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Reqnroll-Test-Videos
        path: /home/runner/work/GoogleYouTube/GoogleYouTube/bin/Release/net8.0/Reports/Results/Videos/
        retention-days: 7
